export const JWT_CONSTANTS = {
  SECRET: process.env.JWT_SECRET_KEY,
  REFRESH_SECRET: process.env.JWT_SECRET_REFRESH_KEY,
  TOKEN_EXPIRATION: process.env.ACCESS_TOKEN_EXPIRATION || '24h',
  REFRESH_TOKEN_EXPIRATION: process.env.REFRESH_TOKEN_EXPIRATION || '48h',
} as const;
