services:
  server:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - server-logs:/app/logs
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresdb:${POSTGRES_PORT}/${POSTGRES_DB}?schema=public
      CRYPT_SALT: ${CRYPT_SALT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_SECRET_REFRESH_KEY: ${JWT_SECRET_REFRESH_KEY}
      TOKEN_EXPIRE_TIME: ${TOKEN_EXPIRE_TIME}
      TOKEN_REFRESH_EXPIRE_TIME: ${TOKEN_REFRESH_EXPIRE_TIME}
    depends_on:
      - postgresdb
    networks:
      - home-library-network

  postgresdb:
    container_name: postgresdb
    image: postgres:17.0-alpine3.20
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    env_file:
    - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGPORT: ${POSTGRES_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - home-library-network

networks:
  home-library-network:
    external: false
    driver: bridge

volumes:
  db-data:
  server-logs:
