services:
  server:
    container_name: server
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - postgresdb
    environment:
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - home-library-network

  postgresdb:
    container_name: postgresdb
    image: postgres:17.0-alpine3.20
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - home-library-network
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  home-library-network:
    driver: bridge

volumes:
  db-data:
    driver: local
